### PR TITLE
Fixdows Logo

### PR DESCRIPTION
**Pull request by jameskorah**
Created a folder called Images in which the Fixdows Logo is uploaded as a JPG file.

### CODE REVIEW

**Comment by Odyssey346** [comment]
Do you have a png version with transparency?

**Review by Odyssey346 — CHANGES_REQUESTED** [review]
I need a standalone PNG version of the logo, as I can't have the entire banner as the logo. Once you can do that, I'll be happy to merge.

**Comment by jameskorah** [comment]
Sure, I'll update that and send it now.

**Comment by jameskorah** [comment]
So I've added 2 files. One is just the logo as a PNG file with a bit of the grey background. The second is just the logo as a PNG file with just the white objects (the logo and the text "Fixdows").

**Comment by Odyssey346** [comment]
thank you, will review later.

**Review by Odyssey346 — APPROVED** [review]
I'll fix some stuff myself, but other than that, it's good.

**Pull request merged**
